-- Généré par data/build_seed.py — ne pas éditer à la main
truncate outfit_history, wardrobe_items, app_users, pipeline_errors restart identity cascade;

insert into app_users (id,name,city,latitude,longitude,preferred_style,default_occasion,cold_sensitivity) values (1,'Alex','Paris',48.8566,2.3522,'casual','quotidien','normal');
insert into app_users (id,name,city,latitude,longitude,preferred_style,default_occasion,cold_sensitivity) values (2,'Sam','Lyon',45.764,4.8357,'chic','travail','frileux');
insert into app_users (id,name,city,latitude,longitude,preferred_style,default_occasion,cold_sensitivity) values (99,'Eval Bot','Paris',48.8566,2.3522,'casual','quotidien','normal');
select setval('app_users_id_seq', (select max(id) from app_users));

-- garde-robe de Alex
insert into wardrobe_items (user_id,dataset_code,name,category,subcategory,color,color_family,warmth,waterproof,styles,formality,material,status) values
(1,1,'T-shirt blanc col rond','base_top','t-shirt','blanc','neutre',1,false,array['casual','streetwear','sport'],1,'coton','available'),
(1,2,'T-shirt noir col rond','base_top','t-shirt','noir','neutre',1,false,array['casual','streetwear','chic'],1,'coton','available'),
(1,3,'T-shirt gris chiné','base_top','t-shirt','gris','neutre',1,false,array['casual','sport'],1,'coton','available'),
(1,4,'T-shirt marinière','base_top','t-shirt','bleu marine','froid',1,false,array['casual','boheme'],2,'coton','available'),
(1,5,'T-shirt graphique oversize','base_top','t-shirt','noir','neutre',1,false,array['streetwear'],1,'coton','available'),
(1,6,'T-shirt technique respirant','base_top','t-shirt','bleu','froid',1,false,array['sport'],1,'polyester','available'),
(1,7,'Débardeur de sport','base_top','debardeur','noir','neutre',0,false,array['sport'],1,'polyester','available'),
(1,8,'Polo piqué bleu marine','base_top','polo','bleu marine','froid',1,false,array['casual','chic'],2,'coton','available'),
(1,9,'Polo blanc','base_top','polo','blanc','neutre',1,false,array['casual','chic'],2,'coton','available'),
(1,10,'Chemise Oxford blanche','base_top','chemise','blanc','neutre',2,false,array['business','chic','casual'],4,'coton','available'),
(1,11,'Chemise Oxford bleu ciel','base_top','chemise','bleu ciel','froid',2,false,array['business','chic'],4,'coton','available'),
(1,12,'Chemise en lin beige','base_top','chemise','beige','chaud',1,false,array['chic','boheme','casual'],3,'lin','available'),
(1,13,'Chemise en jean','base_top','chemise','bleu jean','froid',2,false,array['casual','streetwear'],2,'denim','available'),
(1,14,'Chemise à carreaux flanelle','base_top','chemise','rouge','chaud',3,false,array['casual'],2,'flanelle','available'),
(1,15,'Chemise fleurie manches courtes','base_top','chemise','vert','froid',1,false,array['boheme','casual'],2,'viscose','available'),
(1,16,'Blouse fluide écrue','base_top','blouse','écru','neutre',1,false,array['chic','boheme'],3,'viscose','available'),
(1,17,'T-shirt manches longues crème','base_top','t-shirt','crème','neutre',2,false,array['casual','boheme'],1,'coton','available'),
(1,18,'Sous-pull col roulé noir','base_top','col_roule','noir','neutre',3,false,array['chic','business'],3,'laine mérinos','available'),
(1,19,'Chemise popeline noire','base_top','chemise','noir','neutre',2,false,array['chic','business'],4,'coton','laundry'),
(1,20,'Pull col rond gris','mid_layer','pull','gris','neutre',3,false,array['casual','chic','business'],3,'laine','available'),
(1,21,'Pull col V bleu marine','mid_layer','pull','bleu marine','froid',3,false,array['business','chic'],4,'laine mérinos','available'),
(1,22,'Pull torsadé écru','mid_layer','pull','écru','neutre',4,false,array['casual','boheme'],2,'laine','available'),
(1,23,'Pull col roulé camel','mid_layer','pull','camel','chaud',4,false,array['chic','business'],4,'cachemire','available'),
(1,24,'Sweat à capuche gris','mid_layer','sweat','gris','neutre',3,false,array['streetwear','sport','casual'],1,'coton molletonné','available'),
(1,25,'Sweat col rond noir','mid_layer','sweat','noir','neutre',3,false,array['streetwear','casual'],1,'coton molletonné','available'),
(1,26,'Cardigan vert olive','mid_layer','cardigan','vert olive','chaud',2,false,array['casual','boheme','chic'],3,'laine','available'),
(1,27,'Polaire technique','mid_layer','polaire','bleu','froid',3,false,array['sport'],1,'polaire','available'),
(1,28,'Gilet sans manches matelassé','mid_layer','gilet','bleu marine','froid',2,false,array['casual','business'],3,'nylon','available'),
(1,29,'Blazer bleu marine','mid_layer','blazer','bleu marine','froid',2,false,array['business','chic'],5,'laine','available'),
(1,30,'Blazer beige en lin','mid_layer','blazer','beige','chaud',1,false,array['chic','business','boheme'],4,'lin','available'),
(1,31,'Jean brut slim','bottom','jean','bleu brut','froid',2,false,array['casual','chic','streetwear'],2,'denim','available'),
(1,32,'Jean bleu clair droit','bottom','jean','bleu clair','froid',2,false,array['casual','boheme'],2,'denim','available'),
(1,33,'Jean noir','bottom','jean','noir','neutre',2,false,array['casual','chic','streetwear'],3,'denim','available'),
(1,34,'Chino beige','bottom','chino','beige','chaud',2,false,array['casual','chic','business'],3,'coton','available'),
(1,35,'Chino bleu marine','bottom','chino','bleu marine','froid',2,false,array['casual','chic','business'],3,'coton','available'),
(1,36,'Pantalon de costume gris','bottom','pantalon','gris','neutre',2,false,array['business','chic'],5,'laine','available'),
(1,37,'Pantalon en lin blanc','bottom','pantalon','blanc','neutre',1,false,array['chic','boheme'],3,'lin','available'),
(1,38,'Pantalon cargo kaki','bottom','cargo','kaki','chaud',2,false,array['streetwear','casual'],1,'coton','available'),
(1,39,'Jogging molletonné noir','bottom','jogging','noir','neutre',3,false,array['sport','streetwear'],1,'coton molletonné','available'),
(1,40,'Legging de running','bottom','legging','noir','neutre',1,false,array['sport'],1,'élasthanne','available'),
(1,41,'Short en jean','bottom','short','bleu clair','froid',0,false,array['casual','streetwear'],1,'denim','available'),
(1,42,'Short chino beige','bottom','short','beige','chaud',0,false,array['casual','chic'],2,'coton','available'),
(1,43,'Short de sport','bottom','short','noir','neutre',0,false,array['sport'],1,'polyester','available'),
(1,44,'Jupe midi plissée','bottom','jupe','vert','froid',1,false,array['chic','boheme'],3,'polyester','available'),
(1,45,'Pantalon velours côtelé marron','bottom','pantalon','marron','chaud',3,false,array['casual','boheme','chic'],3,'velours','available'),
(1,46,'Pantalon doublé thermique','bottom','pantalon','noir','neutre',4,true,array['sport','casual'],1,'softshell','available'),
(1,47,'Imperméable léger jaune','outerwear','impermeable','jaune','chaud',1,true,array['casual','streetwear','sport'],1,'nylon','available'),
(1,48,'Trench beige','outerwear','trench','beige','chaud',2,true,array['chic','business','casual'],4,'coton enduit','available'),
(1,49,'Veste en jean','outerwear','veste','bleu jean','froid',2,false,array['casual','streetwear','boheme'],2,'denim','available'),
(1,50,'Blouson en cuir noir','outerwear','blouson','noir','neutre',3,false,array['chic','streetwear','casual'],3,'cuir','available'),
(1,51,'Bomber kaki','outerwear','blouson','kaki','chaud',3,false,array['streetwear','casual'],2,'nylon','available'),
(1,52,'Veste coupe-vent running','outerwear','coupe_vent','orange','chaud',1,true,array['sport'],1,'polyester','available'),
(1,53,'Manteau en laine camel','outerwear','manteau','camel','chaud',4,false,array['chic','business'],5,'laine','available'),
(1,54,'Caban bleu marine','outerwear','manteau','bleu marine','froid',4,false,array['chic','business','casual'],4,'laine','available'),
(1,55,'Doudoune longue noire','outerwear','doudoune','noir','neutre',5,true,array['casual','streetwear','sport'],2,'duvet','available'),
(1,56,'Parka imperméable kaki','outerwear','parka','kaki','chaud',4,true,array['casual','streetwear'],2,'nylon','available'),
(1,57,'Veste de pluie technique','outerwear','impermeable','bleu marine','froid',2,true,array['sport','casual'],1,'Gore-Tex','available'),
(1,58,'Baskets blanches cuir','shoes','baskets','blanc','neutre',1,false,array['casual','chic','streetwear'],2,'cuir','available'),
(1,59,'Sneakers running','shoes','running','gris','neutre',1,false,array['sport'],1,'mesh','available'),
(1,60,'Baskets montantes noires','shoes','baskets','noir','neutre',2,false,array['streetwear','casual'],1,'toile','available'),
(1,61,'Derbies cuir marron','shoes','derbies','marron','chaud',2,false,array['business','chic'],5,'cuir','available'),
(1,62,'Mocassins daim camel','shoes','mocassins','camel','chaud',1,false,array['chic','business','boheme'],4,'daim','available'),
(1,63,'Bottines Chelsea noires','shoes','bottines','noir','neutre',3,true,array['chic','casual','business'],4,'cuir','available'),
(1,64,'Boots de randonnée imperméables','shoes','boots','marron','chaud',4,true,array['sport','casual'],1,'Gore-Tex','available'),
(1,65,'Sandales cuir','shoes','sandales','marron','chaud',0,false,array['boheme','casual'],1,'cuir','available'),
(1,66,'Espadrilles écrues','shoes','espadrilles','écru','neutre',0,false,array['boheme','casual','chic'],2,'toile','available'),
(1,67,'Bottes de pluie','shoes','bottes_pluie','vert','froid',3,true,array['casual'],1,'caoutchouc','available'),
(1,68,'Parapluie compact noir','accessory','parapluie','noir','neutre',0,true,array['casual','chic','business','streetwear','boheme','sport'],3,'nylon','available'),
(1,69,'Lunettes de soleil','accessory','lunettes_soleil','noir','neutre',0,false,array['casual','chic','streetwear','boheme','sport'],2,'acétate','available'),
(1,70,'Casquette','accessory','casquette','beige','chaud',0,false,array['casual','streetwear','sport'],1,'coton','available'),
(1,71,'Bonnet en laine','accessory','bonnet','gris','neutre',2,false,array['casual','streetwear','sport'],1,'laine','available'),
(1,72,'Écharpe en laine','accessory','echarpe','bordeaux','chaud',2,false,array['casual','chic','business','boheme'],3,'laine','available'),
(1,73,'Gants en cuir','accessory','gants','noir','neutre',2,false,array['chic','business','casual'],4,'cuir','available'),
(1,74,'Foulard en soie','accessory','foulard','bleu','froid',0,false,array['chic','boheme'],4,'soie','available'),
(1,75,'Ceinture cuir marron','accessory','ceinture','marron','chaud',0,false,array['business','chic','casual'],4,'cuir','available'),
(1,76,'Montre classique','accessory','montre','argent','neutre',0,false,array['business','chic','casual'],4,'acier','available'),
(1,77,'Tote bag en toile','accessory','sac','écru','neutre',0,false,array['casual','boheme'],1,'toile','available'),
(1,78,'Chapeau de paille','accessory','chapeau','beige','chaud',0,false,array['boheme','casual'],2,'paille','available');

-- garde-robe de Sam
insert into wardrobe_items (user_id,dataset_code,name,category,subcategory,color,color_family,warmth,waterproof,styles,formality,material,status) values
(2,1,'T-shirt blanc col rond','base_top','t-shirt','blanc','neutre',1,false,array['casual','streetwear','sport'],1,'coton','available'),
(2,2,'T-shirt noir col rond','base_top','t-shirt','noir','neutre',1,false,array['casual','streetwear','chic'],1,'coton','available'),
(2,3,'T-shirt gris chiné','base_top','t-shirt','gris','neutre',1,false,array['casual','sport'],1,'coton','available'),
(2,4,'T-shirt marinière','base_top','t-shirt','bleu marine','froid',1,false,array['casual','boheme'],2,'coton','available'),
(2,5,'T-shirt graphique oversize','base_top','t-shirt','noir','neutre',1,false,array['streetwear'],1,'coton','available'),
(2,6,'T-shirt technique respirant','base_top','t-shirt','bleu','froid',1,false,array['sport'],1,'polyester','available'),
(2,7,'Débardeur de sport','base_top','debardeur','noir','neutre',0,false,array['sport'],1,'polyester','available'),
(2,8,'Polo piqué bleu marine','base_top','polo','bleu marine','froid',1,false,array['casual','chic'],2,'coton','available'),
(2,9,'Polo blanc','base_top','polo','blanc','neutre',1,false,array['casual','chic'],2,'coton','available'),
(2,10,'Chemise Oxford blanche','base_top','chemise','blanc','neutre',2,false,array['business','chic','casual'],4,'coton','available'),
(2,11,'Chemise Oxford bleu ciel','base_top','chemise','bleu ciel','froid',2,false,array['business','chic'],4,'coton','available'),
(2,12,'Chemise en lin beige','base_top','chemise','beige','chaud',1,false,array['chic','boheme','casual'],3,'lin','available'),
(2,13,'Chemise en jean','base_top','chemise','bleu jean','froid',2,false,array['casual','streetwear'],2,'denim','available'),
(2,14,'Chemise à carreaux flanelle','base_top','chemise','rouge','chaud',3,false,array['casual'],2,'flanelle','available'),
(2,15,'Chemise fleurie manches courtes','base_top','chemise','vert','froid',1,false,array['boheme','casual'],2,'viscose','available'),
(2,16,'Blouse fluide écrue','base_top','blouse','écru','neutre',1,false,array['chic','boheme'],3,'viscose','available'),
(2,17,'T-shirt manches longues crème','base_top','t-shirt','crème','neutre',2,false,array['casual','boheme'],1,'coton','available'),
(2,18,'Sous-pull col roulé noir','base_top','col_roule','noir','neutre',3,false,array['chic','business'],3,'laine mérinos','available'),
(2,19,'Chemise popeline noire','base_top','chemise','noir','neutre',2,false,array['chic','business'],4,'coton','laundry'),
(2,20,'Pull col rond gris','mid_layer','pull','gris','neutre',3,false,array['casual','chic','business'],3,'laine','available'),
(2,21,'Pull col V bleu marine','mid_layer','pull','bleu marine','froid',3,false,array['business','chic'],4,'laine mérinos','available'),
(2,22,'Pull torsadé écru','mid_layer','pull','écru','neutre',4,false,array['casual','boheme'],2,'laine','available'),
(2,23,'Pull col roulé camel','mid_layer','pull','camel','chaud',4,false,array['chic','business'],4,'cachemire','available'),
(2,24,'Sweat à capuche gris','mid_layer','sweat','gris','neutre',3,false,array['streetwear','sport','casual'],1,'coton molletonné','available'),
(2,25,'Sweat col rond noir','mid_layer','sweat','noir','neutre',3,false,array['streetwear','casual'],1,'coton molletonné','available'),
(2,26,'Cardigan vert olive','mid_layer','cardigan','vert olive','chaud',2,false,array['casual','boheme','chic'],3,'laine','available'),
(2,27,'Polaire technique','mid_layer','polaire','bleu','froid',3,false,array['sport'],1,'polaire','available'),
(2,28,'Gilet sans manches matelassé','mid_layer','gilet','bleu marine','froid',2,false,array['casual','business'],3,'nylon','available'),
(2,29,'Blazer bleu marine','mid_layer','blazer','bleu marine','froid',2,false,array['business','chic'],5,'laine','available'),
(2,30,'Blazer beige en lin','mid_layer','blazer','beige','chaud',1,false,array['chic','business','boheme'],4,'lin','available'),
(2,31,'Jean brut slim','bottom','jean','bleu brut','froid',2,false,array['casual','chic','streetwear'],2,'denim','available'),
(2,32,'Jean bleu clair droit','bottom','jean','bleu clair','froid',2,false,array['casual','boheme'],2,'denim','available'),
(2,33,'Jean noir','bottom','jean','noir','neutre',2,false,array['casual','chic','streetwear'],3,'denim','available'),
(2,34,'Chino beige','bottom','chino','beige','chaud',2,false,array['casual','chic','business'],3,'coton','available'),
(2,35,'Chino bleu marine','bottom','chino','bleu marine','froid',2,false,array['casual','chic','business'],3,'coton','available'),
(2,36,'Pantalon de costume gris','bottom','pantalon','gris','neutre',2,false,array['business','chic'],5,'laine','available'),
(2,37,'Pantalon en lin blanc','bottom','pantalon','blanc','neutre',1,false,array['chic','boheme'],3,'lin','available'),
(2,38,'Pantalon cargo kaki','bottom','cargo','kaki','chaud',2,false,array['streetwear','casual'],1,'coton','available'),
(2,39,'Jogging molletonné noir','bottom','jogging','noir','neutre',3,false,array['sport','streetwear'],1,'coton molletonné','available'),
(2,40,'Legging de running','bottom','legging','noir','neutre',1,false,array['sport'],1,'élasthanne','available'),
(2,41,'Short en jean','bottom','short','bleu clair','froid',0,false,array['casual','streetwear'],1,'denim','available'),
(2,42,'Short chino beige','bottom','short','beige','chaud',0,false,array['casual','chic'],2,'coton','available'),
(2,43,'Short de sport','bottom','short','noir','neutre',0,false,array['sport'],1,'polyester','available'),
(2,44,'Jupe midi plissée','bottom','jupe','vert','froid',1,false,array['chic','boheme'],3,'polyester','available'),
(2,45,'Pantalon velours côtelé marron','bottom','pantalon','marron','chaud',3,false,array['casual','boheme','chic'],3,'velours','available'),
(2,46,'Pantalon doublé thermique','bottom','pantalon','noir','neutre',4,true,array['sport','casual'],1,'softshell','available'),
(2,47,'Imperméable léger jaune','outerwear','impermeable','jaune','chaud',1,true,array['casual','streetwear','sport'],1,'nylon','available'),
(2,48,'Trench beige','outerwear','trench','beige','chaud',2,true,array['chic','business','casual'],4,'coton enduit','available'),
(2,49,'Veste en jean','outerwear','veste','bleu jean','froid',2,false,array['casual','streetwear','boheme'],2,'denim','available'),
(2,50,'Blouson en cuir noir','outerwear','blouson','noir','neutre',3,false,array['chic','streetwear','casual'],3,'cuir','available'),
(2,51,'Bomber kaki','outerwear','blouson','kaki','chaud',3,false,array['streetwear','casual'],2,'nylon','available'),
(2,52,'Veste coupe-vent running','outerwear','coupe_vent','orange','chaud',1,true,array['sport'],1,'polyester','available'),
(2,53,'Manteau en laine camel','outerwear','manteau','camel','chaud',4,false,array['chic','business'],5,'laine','available'),
(2,54,'Caban bleu marine','outerwear','manteau','bleu marine','froid',4,false,array['chic','business','casual'],4,'laine','available'),
(2,55,'Doudoune longue noire','outerwear','doudoune','noir','neutre',5,true,array['casual','streetwear','sport'],2,'duvet','available'),
(2,56,'Parka imperméable kaki','outerwear','parka','kaki','chaud',4,true,array['casual','streetwear'],2,'nylon','available'),
(2,57,'Veste de pluie technique','outerwear','impermeable','bleu marine','froid',2,true,array['sport','casual'],1,'Gore-Tex','available'),
(2,58,'Baskets blanches cuir','shoes','baskets','blanc','neutre',1,false,array['casual','chic','streetwear'],2,'cuir','available'),
(2,59,'Sneakers running','shoes','running','gris','neutre',1,false,array['sport'],1,'mesh','available'),
(2,60,'Baskets montantes noires','shoes','baskets','noir','neutre',2,false,array['streetwear','casual'],1,'toile','available'),
(2,61,'Derbies cuir marron','shoes','derbies','marron','chaud',2,false,array['business','chic'],5,'cuir','available'),
(2,62,'Mocassins daim camel','shoes','mocassins','camel','chaud',1,false,array['chic','business','boheme'],4,'daim','available'),
(2,63,'Bottines Chelsea noires','shoes','bottines','noir','neutre',3,true,array['chic','casual','business'],4,'cuir','available'),
(2,64,'Boots de randonnée imperméables','shoes','boots','marron','chaud',4,true,array['sport','casual'],1,'Gore-Tex','available'),
(2,65,'Sandales cuir','shoes','sandales','marron','chaud',0,false,array['boheme','casual'],1,'cuir','available'),
(2,66,'Espadrilles écrues','shoes','espadrilles','écru','neutre',0,false,array['boheme','casual','chic'],2,'toile','available'),
(2,67,'Bottes de pluie','shoes','bottes_pluie','vert','froid',3,true,array['casual'],1,'caoutchouc','available'),
(2,68,'Parapluie compact noir','accessory','parapluie','noir','neutre',0,true,array['casual','chic','business','streetwear','boheme','sport'],3,'nylon','available'),
(2,69,'Lunettes de soleil','accessory','lunettes_soleil','noir','neutre',0,false,array['casual','chic','streetwear','boheme','sport'],2,'acétate','available'),
(2,70,'Casquette','accessory','casquette','beige','chaud',0,false,array['casual','streetwear','sport'],1,'coton','available'),
(2,71,'Bonnet en laine','accessory','bonnet','gris','neutre',2,false,array['casual','streetwear','sport'],1,'laine','available'),
(2,72,'Écharpe en laine','accessory','echarpe','bordeaux','chaud',2,false,array['casual','chic','business','boheme'],3,'laine','available'),
(2,73,'Gants en cuir','accessory','gants','noir','neutre',2,false,array['chic','business','casual'],4,'cuir','available'),
(2,74,'Foulard en soie','accessory','foulard','bleu','froid',0,false,array['chic','boheme'],4,'soie','available'),
(2,75,'Ceinture cuir marron','accessory','ceinture','marron','chaud',0,false,array['business','chic','casual'],4,'cuir','available'),
(2,76,'Montre classique','accessory','montre','argent','neutre',0,false,array['business','chic','casual'],4,'acier','available'),
(2,77,'Tote bag en toile','accessory','sac','écru','neutre',0,false,array['casual','boheme'],1,'toile','available'),
(2,78,'Chapeau de paille','accessory','chapeau','beige','chaud',0,false,array['boheme','casual'],2,'paille','available');

-- garde-robe de Eval Bot
insert into wardrobe_items (user_id,dataset_code,name,category,subcategory,color,color_family,warmth,waterproof,styles,formality,material,status) values
(99,1,'T-shirt blanc col rond','base_top','t-shirt','blanc','neutre',1,false,array['casual','streetwear','sport'],1,'coton','available'),
(99,2,'T-shirt noir col rond','base_top','t-shirt','noir','neutre',1,false,array['casual','streetwear','chic'],1,'coton','available'),
(99,3,'T-shirt gris chiné','base_top','t-shirt','gris','neutre',1,false,array['casual','sport'],1,'coton','available'),
(99,4,'T-shirt marinière','base_top','t-shirt','bleu marine','froid',1,false,array['casual','boheme'],2,'coton','available'),
(99,5,'T-shirt graphique oversize','base_top','t-shirt','noir','neutre',1,false,array['streetwear'],1,'coton','available'),
(99,6,'T-shirt technique respirant','base_top','t-shirt','bleu','froid',1,false,array['sport'],1,'polyester','available'),
(99,7,'Débardeur de sport','base_top','debardeur','noir','neutre',0,false,array['sport'],1,'polyester','available'),
(99,8,'Polo piqué bleu marine','base_top','polo','bleu marine','froid',1,false,array['casual','chic'],2,'coton','available'),
(99,9,'Polo blanc','base_top','polo','blanc','neutre',1,false,array['casual','chic'],2,'coton','available'),
(99,10,'Chemise Oxford blanche','base_top','chemise','blanc','neutre',2,false,array['business','chic','casual'],4,'coton','available'),
(99,11,'Chemise Oxford bleu ciel','base_top','chemise','bleu ciel','froid',2,false,array['business','chic'],4,'coton','available'),
(99,12,'Chemise en lin beige','base_top','chemise','beige','chaud',1,false,array['chic','boheme','casual'],3,'lin','available'),
(99,13,'Chemise en jean','base_top','chemise','bleu jean','froid',2,false,array['casual','streetwear'],2,'denim','available'),
(99,14,'Chemise à carreaux flanelle','base_top','chemise','rouge','chaud',3,false,array['casual'],2,'flanelle','available'),
(99,15,'Chemise fleurie manches courtes','base_top','chemise','vert','froid',1,false,array['boheme','casual'],2,'viscose','available'),
(99,16,'Blouse fluide écrue','base_top','blouse','écru','neutre',1,false,array['chic','boheme'],3,'viscose','available'),
(99,17,'T-shirt manches longues crème','base_top','t-shirt','crème','neutre',2,false,array['casual','boheme'],1,'coton','available'),
(99,18,'Sous-pull col roulé noir','base_top','col_roule','noir','neutre',3,false,array['chic','business'],3,'laine mérinos','available'),
(99,19,'Chemise popeline noire','base_top','chemise','noir','neutre',2,false,array['chic','business'],4,'coton','available'),
(99,20,'Pull col rond gris','mid_layer','pull','gris','neutre',3,false,array['casual','chic','business'],3,'laine','available'),
(99,21,'Pull col V bleu marine','mid_layer','pull','bleu marine','froid',3,false,array['business','chic'],4,'laine mérinos','available'),
(99,22,'Pull torsadé écru','mid_layer','pull','écru','neutre',4,false,array['casual','boheme'],2,'laine','available'),
(99,23,'Pull col roulé camel','mid_layer','pull','camel','chaud',4,false,array['chic','business'],4,'cachemire','available'),
(99,24,'Sweat à capuche gris','mid_layer','sweat','gris','neutre',3,false,array['streetwear','sport','casual'],1,'coton molletonné','available'),
(99,25,'Sweat col rond noir','mid_layer','sweat','noir','neutre',3,false,array['streetwear','casual'],1,'coton molletonné','available'),
(99,26,'Cardigan vert olive','mid_layer','cardigan','vert olive','chaud',2,false,array['casual','boheme','chic'],3,'laine','available'),
(99,27,'Polaire technique','mid_layer','polaire','bleu','froid',3,false,array['sport'],1,'polaire','available'),
(99,28,'Gilet sans manches matelassé','mid_layer','gilet','bleu marine','froid',2,false,array['casual','business'],3,'nylon','available'),
(99,29,'Blazer bleu marine','mid_layer','blazer','bleu marine','froid',2,false,array['business','chic'],5,'laine','available'),
(99,30,'Blazer beige en lin','mid_layer','blazer','beige','chaud',1,false,array['chic','business','boheme'],4,'lin','available'),
(99,31,'Jean brut slim','bottom','jean','bleu brut','froid',2,false,array['casual','chic','streetwear'],2,'denim','available'),
(99,32,'Jean bleu clair droit','bottom','jean','bleu clair','froid',2,false,array['casual','boheme'],2,'denim','available'),
(99,33,'Jean noir','bottom','jean','noir','neutre',2,false,array['casual','chic','streetwear'],3,'denim','available'),
(99,34,'Chino beige','bottom','chino','beige','chaud',2,false,array['casual','chic','business'],3,'coton','available'),
(99,35,'Chino bleu marine','bottom','chino','bleu marine','froid',2,false,array['casual','chic','business'],3,'coton','available'),
(99,36,'Pantalon de costume gris','bottom','pantalon','gris','neutre',2,false,array['business','chic'],5,'laine','available'),
(99,37,'Pantalon en lin blanc','bottom','pantalon','blanc','neutre',1,false,array['chic','boheme'],3,'lin','available'),
(99,38,'Pantalon cargo kaki','bottom','cargo','kaki','chaud',2,false,array['streetwear','casual'],1,'coton','available'),
(99,39,'Jogging molletonné noir','bottom','jogging','noir','neutre',3,false,array['sport','streetwear'],1,'coton molletonné','available'),
(99,40,'Legging de running','bottom','legging','noir','neutre',1,false,array['sport'],1,'élasthanne','available'),
(99,41,'Short en jean','bottom','short','bleu clair','froid',0,false,array['casual','streetwear'],1,'denim','available'),
(99,42,'Short chino beige','bottom','short','beige','chaud',0,false,array['casual','chic'],2,'coton','available'),
(99,43,'Short de sport','bottom','short','noir','neutre',0,false,array['sport'],1,'polyester','available'),
(99,44,'Jupe midi plissée','bottom','jupe','vert','froid',1,false,array['chic','boheme'],3,'polyester','available'),
(99,45,'Pantalon velours côtelé marron','bottom','pantalon','marron','chaud',3,false,array['casual','boheme','chic'],3,'velours','available'),
(99,46,'Pantalon doublé thermique','bottom','pantalon','noir','neutre',4,true,array['sport','casual'],1,'softshell','available'),
(99,47,'Imperméable léger jaune','outerwear','impermeable','jaune','chaud',1,true,array['casual','streetwear','sport'],1,'nylon','available'),
(99,48,'Trench beige','outerwear','trench','beige','chaud',2,true,array['chic','business','casual'],4,'coton enduit','available'),
(99,49,'Veste en jean','outerwear','veste','bleu jean','froid',2,false,array['casual','streetwear','boheme'],2,'denim','available'),
(99,50,'Blouson en cuir noir','outerwear','blouson','noir','neutre',3,false,array['chic','streetwear','casual'],3,'cuir','available'),
(99,51,'Bomber kaki','outerwear','blouson','kaki','chaud',3,false,array['streetwear','casual'],2,'nylon','available'),
(99,52,'Veste coupe-vent running','outerwear','coupe_vent','orange','chaud',1,true,array['sport'],1,'polyester','available'),
(99,53,'Manteau en laine camel','outerwear','manteau','camel','chaud',4,false,array['chic','business'],5,'laine','available'),
(99,54,'Caban bleu marine','outerwear','manteau','bleu marine','froid',4,false,array['chic','business','casual'],4,'laine','available'),
(99,55,'Doudoune longue noire','outerwear','doudoune','noir','neutre',5,true,array['casual','streetwear','sport'],2,'duvet','available'),
(99,56,'Parka imperméable kaki','outerwear','parka','kaki','chaud',4,true,array['casual','streetwear'],2,'nylon','available'),
(99,57,'Veste de pluie technique','outerwear','impermeable','bleu marine','froid',2,true,array['sport','casual'],1,'Gore-Tex','available'),
(99,58,'Baskets blanches cuir','shoes','baskets','blanc','neutre',1,false,array['casual','chic','streetwear'],2,'cuir','available'),
(99,59,'Sneakers running','shoes','running','gris','neutre',1,false,array['sport'],1,'mesh','available'),
(99,60,'Baskets montantes noires','shoes','baskets','noir','neutre',2,false,array['streetwear','casual'],1,'toile','available'),
(99,61,'Derbies cuir marron','shoes','derbies','marron','chaud',2,false,array['business','chic'],5,'cuir','available'),
(99,62,'Mocassins daim camel','shoes','mocassins','camel','chaud',1,false,array['chic','business','boheme'],4,'daim','available'),
(99,63,'Bottines Chelsea noires','shoes','bottines','noir','neutre',3,true,array['chic','casual','business'],4,'cuir','available'),
(99,64,'Boots de randonnée imperméables','shoes','boots','marron','chaud',4,true,array['sport','casual'],1,'Gore-Tex','available'),
(99,65,'Sandales cuir','shoes','sandales','marron','chaud',0,false,array['boheme','casual'],1,'cuir','available'),
(99,66,'Espadrilles écrues','shoes','espadrilles','écru','neutre',0,false,array['boheme','casual','chic'],2,'toile','available'),
(99,67,'Bottes de pluie','shoes','bottes_pluie','vert','froid',3,true,array['casual'],1,'caoutchouc','available'),
(99,68,'Parapluie compact noir','accessory','parapluie','noir','neutre',0,true,array['casual','chic','business','streetwear','boheme','sport'],3,'nylon','available'),
(99,69,'Lunettes de soleil','accessory','lunettes_soleil','noir','neutre',0,false,array['casual','chic','streetwear','boheme','sport'],2,'acétate','available'),
(99,70,'Casquette','accessory','casquette','beige','chaud',0,false,array['casual','streetwear','sport'],1,'coton','available'),
(99,71,'Bonnet en laine','accessory','bonnet','gris','neutre',2,false,array['casual','streetwear','sport'],1,'laine','available'),
(99,72,'Écharpe en laine','accessory','echarpe','bordeaux','chaud',2,false,array['casual','chic','business','boheme'],3,'laine','available'),
(99,73,'Gants en cuir','accessory','gants','noir','neutre',2,false,array['chic','business','casual'],4,'cuir','available'),
(99,74,'Foulard en soie','accessory','foulard','bleu','froid',0,false,array['chic','boheme'],4,'soie','available'),
(99,75,'Ceinture cuir marron','accessory','ceinture','marron','chaud',0,false,array['business','chic','casual'],4,'cuir','available'),
(99,76,'Montre classique','accessory','montre','argent','neutre',0,false,array['business','chic','casual'],4,'acier','available'),
(99,77,'Tote bag en toile','accessory','sac','écru','neutre',0,false,array['casual','boheme'],1,'toile','available'),
(99,78,'Chapeau de paille','accessory','chapeau','beige','chaud',0,false,array['boheme','casual'],2,'paille','available');
